### ISSUE TITLE
Связать истоки горизонталями

### ISSUE THREAD

**Issue by alistkova** [citec-spbu/RiverNetwork-GISTools#10]
Для решения этой задачи нужно было найти истоки на примерно одинаковой высоте и соединить их горизонтальными линиями. Если между точками есть горизонтальный путь с перепадом высот, то стоит отобразить его. В случае наличия нескольких таких путей показать все. Если путь возможен только с большим прогибом вниз, точки считаются несвязанными.

**Comment by mus0roprovod** [comment]
Коммит, который связан с данным issue: [8e18f3a](https://github.com/citec-spbu/RiverNetwork-GISTools/commit/83dbba3)
