### ISSUE TITLE
Обработка спутниковых снимков

### ISSUE THREAD

**Issue by alistkova** [citec-spbu/RiverNetwork-GISTools#6]
◦ построить карту рельефа по спутниковым снимкам
        ◦ предложить способ, как учесть ошибку в спутниковых данных из-за высокого леса
            ▪ оператор может проставить контрольные точки
        ◦ улучшить алгоритм построения рельефа с учетом высоты лесного покрова на спутниковых снимках высот
        ◦ дать оператору инструмент для корректировки результатов

    Результат:
        ◦ слой с картой рельефа без коррекции по растительности
        ◦ слой с корректированной по растительности картой высот
        ◦ выделить расхождения между этими слоями

**Comment by mus0roprovod** [comment]
Коммит, который отражает реализацию данного этапа: [8e18f3a](https://github.com/citec-spbu/RiverNetwork-GISTools/commit/8e18f3a)
