### ISSUE TITLE
Создать алгоритмы выделения границ зон основных и промежуточных водоразделов

### ISSUE THREAD

**Issue by alistkova** [citec-spbu/RiverNetwork-GISTools#7]
Что сделать:
        ◦ по карте речной сети определить истоки рек 
            ▪ по перепаду высот видим, где начало
        ◦ совместить и уточнить карту речной сети информацией об истоках рек из csv файла
        ◦ по карте рельефа и истоков связать истоки геодезическими линиями 
        ◦ определить потенциальные зоны водоразделов рек на основе связанных истоков
        ◦ определить зоны, где ситуация очевидна и где требуется ручное вмешательство оператора
        ◦ определить водосбор реки как зону между окружающими водоразделами
        ◦ предложить критерии достоверности полученных областей
        ◦ дать инструмент оператору для уточнения результатов
        ◦ дать инструмент оператору позволяющий для заданной точки на реке подсветить ее истоки и притоки, ее водосбор
    Результат:
        ◦ слой в Q-GIS с границами основного водораздела, промежуточных водоразделов и водосбора реки для ПТ

**Comment by mus0roprovod** [comment]
Связанный c issue коммит: [8e18f3a](https://github.com/citec-spbu/RiverNetwork-GISTools/commit/8e18f3a)
