### ISSUE TITLE
Реализация алгоритма  расчета сети ветрозащитных лесополос

### ISSUE THREAD

**Issue by alistkova** [citec-spbu/RiverNetwork-GISTools#8]
Реаилизована задача по распределению  на местности в заданном регионе, на приводораздельной зоне, ветрозащитные лесополосы: располагаемые на необходимом и достаточном расстоянии друг от друга, по горизонталям, без учета розы ветров. Для достиденяи этого было рассчитано идеальное расстояние между лесополосами и уже на оптимальном расстоянии (h_op) создаются лесополосы для каждой изолинии.

**Comment by mus0roprovod** [comment]
Связанный коммит: [8e18f3a](https://github.com/citec-spbu/RiverNetwork-GISTools/commit/6300b9f)
