### ISSUE TITLE
Показать точки истоков

### ISSUE THREAD

**Issue by alistkova** [citec-spbu/RiverNetwork-GISTools#9]
Для реализации данного алгоритма необходимо было брать точку с максимальной высотой на линии реки, как точку истока. Тогда  высотой истока будем считать максимальную высоту в «зоне» этого истока
(зоной считать круг вокруг истока с горизонтальным радиусом = M метров, где M параметр скрипта).
При этом горизонтальные координаты точки оставлять исходными.

**Comment by mus0roprovod** [comment]
Коммит, который связан с данным issue: [8e18f3a](https://github.com/citec-spbu/RiverNetwork-GISTools/commit/337018e)
